### ISSUE TITLE
PhyloMad cannot open file (test for saturation)

### ISSUE THREAD

**Issue by YasminAsar97** [duchene/phylomad#5]
Hi Dr. Duchêne, 

I am running PhyloMad on macOS Big Sur to test for saturation in my sequence alignments. However, I get the following error message:

"Warning in file(filename, "r", encoding = encoding) :
  cannot open file 'testBackbones/Saturation/test.server.R': No such file or directory

Warning: Error in file: cannot open the connection
  101: file
  100: source
   99: renderPrint
   98: func
   82: renderFunc
   81: output$out6cf095dd80759682
    1: runApp"

Do you have any idea what may be causing this issue? I checked the testBackbones folder, and the test.server.R file is definitely there. 

**Also**, sometimes this is an issue, but sometimes PhyloMad works perfectly fine, I am not sure what causes it! It seems to happen if a run was interrupted by an error. I.e. after any error with the analysis occurs I will get this error message no matter what I am running, until I restart PhyloMad. Perhaps this is a bug?

Thanks,
Yasmin

**Comment by YasminAsar97** [comment]
Also, another issue I have when testing for saturation (again, with the option "Remove sites with missing data") is: 

"Error in clean.gene(sdata = loc, format = dataFormat, aadata = aadata,  : 
  Too many sites have missing data
Warning: Error in [[: subscript out of bounds"

I should note that using PhyloMad to test for saturation when I use the option "1st+2nd versus 3rd codon positions" works perfectly fine! 

Thanks,
Yasmin

**Comment by YasminAsar97** [comment]
Hi, 

Also, when I try to test for saturation using the option "Remove sites with missing data", the following error message appears:

"Error in clean.gene(sdata = loc, format = dataFormat, aadata = aadata,  : 
  Too many sites have missing data
Warning: Error in [[: subscript out of bounds"

I do not get this error when I test for saturation using the option "1st+2nd versus 3rd codon positions". Is there any way of getting around this issue (apart from having sequence alignments without gaps)? 

Thanks,
Yasmin

**Comment by duchene** [comment]
Hi Yasmin,
Indeed, once the software is interrupted with an error it needs to be closed down and reopened. This can be a hassle but is a tricky one to solve in these Shiny apps.
Your second issue seems to be associated with excessive missing data. You can choose the option "Test complete data set" to simply ignore missing data.
I will close the issue for now, but do get in touch if these issues persist.
Regards,
David
