### ISSUE TITLE
Error:subscript out of bounds

### ISSUE THREAD

**Issue by quattrinia** [duchene/phylomad#6]
Hi there,

Running Phylomad for the first time. I received this error
Loading required package: shiny
Loading required package: phangorn
Loading required package: ape
Loading required package: foreach
Loading required package: doParallel
Loading required package: iterators
Loading required package: parallel
Loading required package: phytools
Loading required package: maps
Loading required package: apTreeshape
Registered S3 method overwritten by 'apTreeshape':
  method          from
  is.binary.phylo ape 

Attaching package: ‘apTreeshape’

The following object is masked from ‘package:ape’:

    is.binary.phylo

Loading required package: ggtern
Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘ggtern’
2: package ‘ggtern’ is not available (for R version 3.6.3) 
Loading required package: shinyBS

Listening on http://127.0.0.1:4082
Warning in e$fun(obj, substitute(ex), parent.frame(), e$data) :
  already exporting variable(s): linmods
Warning: Error in [[: subscript out of bounds
  107: eval
  106: eval
  104: source
   99: renderPrint
   98: func
   82: origRenderFunc
   81: output$outaec4e0837613a549
    1: runApp

I have tried inputing fasta and phylip formated files. I am running this on just one file-an alignment of ~100 taxa and 18K bp (a mito genome alignment). I am afraid I am missing something?

Any advice would be appreciated! Thank you~

**Comment by duchene** [comment]
Hi Andrea,
It looks like this could be associated with writing the figures. Could you un-tick any boxes in the output tab related to plots and figures, and run PhyloMAd again? Let me know in case this doesn't work. It is a rather intriguing error...
Cheers,
David

**Comment by quattrinia** [comment]
Thanks. I tried that, and got same error. I also loaded R 4.0...thought it could be related to that. That didn't work. Maybe it is my file. (weird character ?). I will try a few things and get back to you.

Loading required package: shiny
Warning message:
The packages `ellipsis` (>= 0.3.2) and `vctrs` (>= 0.3.8) are required as of rlang 1.0.0. 
Loading required package: phangorn
Loading required package: ape
Loading required package: foreach
Warning message:
package ‘foreach’ was built under R version 4.0.5 
Loading required package: doParallel
Loading required package: iterators
Loading required package: parallel
Warning messages:
1: package ‘doParallel’ was built under R version 4.0.5 
2: package ‘iterators’ was built under R version 4.0.5 
Loading required package: phytools
Loading required package: maps
Loading required package: apTreeshape
Registered S3 method overwritten by 'apTreeshape':
  method          from
  is.binary.phylo ape 

Attaching package: ‘apTreeshape’

The following object is masked from ‘package:ape’:

    is.binary.phylo

Loading required package: ggtern
Loading required package: ggplot2
Registered S3 methods overwritten by 'ggtern':
  method           from   
  grid.draw.ggplot ggplot2
  plot.ggplot      ggplot2
  print.ggplot     ggplot2
--
Remember to cite, run citation(package = 'ggtern') for further info.
--

Attaching package: ‘ggtern’

The following objects are masked from ‘package:ggplot2’:

    aes, annotate, ggplot, ggplot_build, ggplot_gtable, ggplotGrob,
    ggsave, layer_data, theme_bw, theme_classic, theme_dark,
    theme_gray, theme_light, theme_linedraw, theme_minimal, theme_void

Warning messages:
1: replacing previous import ‘lifecycle::last_warnings’ by ‘rlang::last_warnings’ when loading ‘tibble’ 
2: replacing previous import ‘ellipsis::check_dots_unnamed’ by ‘rlang::check_dots_unnamed’ when loading ‘tibble’ 
3: replacing previous import ‘ellipsis::check_dots_used’ by ‘rlang::check_dots_used’ when loading ‘tibble’ 
4: replacing previous import ‘ellipsis::check_dots_empty’ by ‘rlang::check_dots_empty’ when loading ‘tibble’ 
5: replacing previous import ‘lifecycle::last_warnings’ by ‘rlang::last_warnings’ when loading ‘pillar’ 
6: replacing previous import ‘ellipsis::check_dots_unnamed’ by ‘rlang::check_dots_unnamed’ when loading ‘pillar’ 
7: replacing previous import ‘ellipsis::check_dots_used’ by ‘rlang::check_dots_used’ when loading ‘pillar’ 
8: replacing previous import ‘ellipsis::check_dots_empty’ by ‘rlang::check_dots_empty’ when loading ‘pillar’ 
Loading required package: shinyBS

Listening on http://127.0.0.1:7345
Warning in e$fun(obj, substitute(ex), parent.frame(), e$data) :
  already exporting variable(s): linmods
Warning: Error in [[: subscript out of bounds

**Comment by quattrinia** [comment]
Ok. It has to do with # cores. Seems to run ok on 1 core, and the plots were created ok. 

I am running this in my laptop with 4 cores. Any workarounds to this?
Thanks!

**Comment by duchene** [comment]
Great to hear that you managed to run PhyloMAd! I must say that the error message and the source are a bit surprising. One possible solution to run with multiple cores is to make sure you have the packages foreach and doParallel, and even separately install them in case that helps solve the issue. For the time being I will close the issue and do let me know if something arises that impedes running altogether (or get in touch with me directly at david.duchene@sund.ku.dk).
