### ISSUE TITLE
cannot change working directory

### ISSUE THREAD

**Issue by NiklausMikaelson12138** [duchene/phylomad#8]
cannot change working directory while running PhyloMAd?  How can I fix it.

**Comment by duchene** [comment]
This error tends to occur when the directory that you have set for the output does not exist, often because there is a typo. Please check whether the directory written is a path to a folder (not a specific file), and let me know how that goes?

**Comment by NiklausMikaelson12138** [comment]
The output path exist. The error goes likes this 
Warning in system(paste0("mkdir ", as.character(input$dataPath[j, 1]), ".phylomad.subst")) :
  'mkdir' not found
Warning: Error in setwd: 无法改变工作目录
  109: setwd
  100: renderPrint
   99: func
   83: renderFunc
   82: output$outcfa482e67115397b
    1: runApp

**Comment by duchene** [comment]
Are you using a mac computer? Unfortunately right now PhyloMAd is only working on macs. I hope to fix this in the near future. Apologies for this inconvenience.

**Comment by NiklausMikaelson12138** [comment]
It is a pity. I am running by windows. Thank you!
