### ISSUE TITLE
Substitutional saturation test output

### ISSUE THREAD

**Issue by lachlan-coff** [duchene/phylomad#9]
Hi David,

Section 5 of the manual has not yet been updated to describe the test for substitutional saturation. I have a few questions on its usage:
- Are codon alignments in FASTA format acceptable inputs for this test?
- Does this test uses the entropy _t_-statistic described in your [2022 publication](https://doi.org/10.1093/sysbio/syab075)?
- Could you please explain the output of this test, including each of the abbreviations (t_predicted_TPR etc.), and how best to interpret the results?

Thank you,

Lachlan

**Comment by duchene** [comment]
Dear Lachlan,

Thanks for your message and questions.
- Yes, you can use FASTA, NEXUS, and phylip formats.
- Yes, the test uses the entropy test in the Syst Biol publication.
- Absolutely. The t_Entropy and t_Entropy_var are the test statistics on the full data set and parsimony-informative sites, respectively. The predicted threshold is the point at which data are likely to be misleading. However, this threshold might have some error, which we provide as a true-positive rate (TPR) and false-positive rate (FPR). These are the expected probabilities that your data and the threshold will lead to true-positives and false positives, respectively. Finally, the Risk_entropy just indicates whether the data are within the threshold (low.risk) or past the threshold (high.risk).

I hope those are intuitive and useful. Please let me know if you have any further questions. I will close the issue for the time being, but feel free to open a new one.

Regards,

David
